// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhtmQXSF2LSaEa7KwyGNmSsC5DfKvBSVU',
    appId: '1:80355689045:web:8eedcca01b5a962f288adc',
    messagingSenderId: '80355689045',
    projectId: 'fluttervirtualhospital',
    authDomain: 'fluttervirtualhospital.firebaseapp.com',
    storageBucket: 'fluttervirtualhospital.appspot.com',
    measurementId: 'G-DFEFQBNS3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6hRt4w4aJ5Da9qYTo0cC1YTqQtjeWQNI',
    appId: '1:80355689045:android:50595bc25709e1e1288adc',
    messagingSenderId: '80355689045',
    projectId: 'fluttervirtualhospital',
    storageBucket: 'fluttervirtualhospital.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeFuBWc5zcZN2m98Xh_Az2U1a_42Dv3XY',
    appId: '1:80355689045:ios:34449135067db148288adc',
    messagingSenderId: '80355689045',
    projectId: 'fluttervirtualhospital',
    storageBucket: 'fluttervirtualhospital.appspot.com',
    iosBundleId: 'com.example.virtualSwaahth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeFuBWc5zcZN2m98Xh_Az2U1a_42Dv3XY',
    appId: '1:80355689045:ios:34449135067db148288adc',
    messagingSenderId: '80355689045',
    projectId: 'fluttervirtualhospital',
    storageBucket: 'fluttervirtualhospital.appspot.com',
    iosBundleId: 'com.example.virtualSwaahth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhtmQXSF2LSaEa7KwyGNmSsC5DfKvBSVU',
    appId: '1:80355689045:web:91af5b5e2de4c903288adc',
    messagingSenderId: '80355689045',
    projectId: 'fluttervirtualhospital',
    authDomain: 'fluttervirtualhospital.firebaseapp.com',
    storageBucket: 'fluttervirtualhospital.appspot.com',
    measurementId: 'G-1E65HG7FBN',
  );
}
